server:
  port: 8087

auth:
  enabled: false
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://localhost:30081/oauth2/jwks

sales-service:
  url: http://localhost:30085

stripe:
  apiKey: ${STRIPE_API_KEY:sk_test_51SBx0NH1LGmpXQLTMttHXOrB9QNPYnWRT5bIzS5W33eDJsX836XTfHKSkwmXFNd4Crnbqwh6XKm8Lu0yoeqdSPBt00evCK3s0C}    # recommended: override with env var
  webhookSecret: ${STRIPE_WEBHOOK_SECRET:whsec_a4f1e7714e26b32a81c5fdf030687e926f18b2ef7b73df35b76ec12731efd43a}

spring:
  application:
    name: Payment

  datasource:
    url: jdbc:mysql://localhost:30310/RPPaymentDB #3300
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    datasource: 
      hikari: # HikariCP Configuration
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
    com.retailpulse: DEBUG
  file:
    name: logs/rp-sales.log