server:
  port: 8087

auth:
  enabled: false
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://localhost:30081/oauth2/jwks

stripe:
  apiKey: ${STRIPE_API_KEY:sk_test_51Rwa98Fo0IYXjs5fnTRUlbpN0TwKCHV2GhVI1hfCM1oI8bMYfP1aYetD8hC9vYazOAoR9fd6AvxV9dn9eanK98Wo00voU4Crd8}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET:whsec_53d63261913c1329c7f48c310297ac40b4d0ef6bb1f6bc3f541af4b6114cf3a7}

#topic name for payment events
app:
  kafka:
    topic:
      payment-events: payment-events
      payment-events-dlt: payment-events-dlt

spring:
  application:
    name: Payment

  datasource:
    url: jdbc:mysql://localhost:30310/RPPaymentDB #3300
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # HikariCP Configuration
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    user:
      name: admin
      password: admin

  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:kafka-service.ns-retailpulse.svc.cluster.local:9092}
    template:
      default-topic: payment-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 10
        enable.idempotence: true
        spring.json.add.type.headers: false

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

sales-service:
  url: http://localhost:30085

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
    com.retailpulse: DEBUG
  file:
    name: logs/rp-sales.log
